"""entries table

Revision ID: 0168277ae192
Revises: bb29dde66e38
Create Date: 2024-05-18 15:12:14.173500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0168277ae192'
down_revision = 'bb29dde66e38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jewelry', sa.Column('price', sa.Float(), nullable=False))
    op.drop_index('ix_jewelry_owner_id', table_name='jewelry')
    op.create_index(op.f('ix_jewelry_price'), 'jewelry', ['price'], unique=False)
    op.drop_column('jewelry', 'is_available')
    op.drop_column('jewelry', 'owner_id')
    op.drop_index('ix_purchase_price', table_name='purchase')
    op.drop_column('purchase', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('price', sa.FLOAT(), nullable=False))
    op.create_index('ix_purchase_price', 'purchase', ['price'], unique=False)
    op.add_column('jewelry', sa.Column('owner_id', sa.INTEGER(), nullable=True))
    op.add_column('jewelry', sa.Column('is_available', sa.BOOLEAN(), nullable=True))
    op.drop_index(op.f('ix_jewelry_price'), table_name='jewelry')
    op.create_index('ix_jewelry_owner_id', 'jewelry', ['owner_id'], unique=False)
    op.drop_column('jewelry', 'price')
    # ### end Alembic commands ###
