"""entries table

Revision ID: 0763c0f8478a
Revises: 0168277ae192
Create Date: 2024-05-18 15:32:11.525805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0763c0f8478a'
down_revision = '0168277ae192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comm',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('surname', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comm_name'), 'comm', ['name'], unique=False)
    op.create_index(op.f('ix_comm_surname'), 'comm', ['surname'], unique=False)
    op.drop_index('ix_owner_name', table_name='owner')
    op.drop_index('ix_owner_surname', table_name='owner')
    op.drop_table('owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('surname', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_owner_surname', 'owner', ['surname'], unique=False)
    op.create_index('ix_owner_name', 'owner', ['name'], unique=False)
    op.drop_index(op.f('ix_comm_surname'), table_name='comm')
    op.drop_index(op.f('ix_comm_name'), table_name='comm')
    op.drop_table('comm')
    # ### end Alembic commands ###
