"""entries table

Revision ID: 46dcd6a2f6b5
Revises: fa9919816299
Create Date: 2024-04-12 22:29:22.596665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46dcd6a2f6b5'
down_revision = 'fa9919816299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jewelery_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_date'), 'purchase', ['date'], unique=False)
    op.create_index(op.f('ix_purchase_jewelery_id'), 'purchase', ['jewelery_id'], unique=False)
    op.add_column('jewelry', sa.Column('is_available', sa.Boolean(), nullable=True))
    op.add_column('jewelry', sa.Column('is_bought', sa.Boolean(), nullable=True))
    op.drop_column('jewelry', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jewelry', sa.Column('status', sa.BOOLEAN(), nullable=True))
    op.drop_column('jewelry', 'is_bought')
    op.drop_column('jewelry', 'is_available')
    op.drop_index(op.f('ix_purchase_jewelery_id'), table_name='purchase')
    op.drop_index(op.f('ix_purchase_date'), table_name='purchase')
    op.drop_table('purchase')
    # ### end Alembic commands ###
