"""entries table

Revision ID: 4b237dc20234
Revises: 70d88dee5373
Create Date: 2024-04-22 21:46:33.052390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b237dc20234'
down_revision = '70d88dee5373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_owner_name'), 'owner', ['name'], unique=False)
    op.create_table('sale',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jewelery_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_date'), 'sale', ['date'], unique=False)
    op.create_index(op.f('ix_sale_jewelery_id'), 'sale', ['jewelery_id'], unique=False)
    op.add_column('jewelry', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_index('ix_jewelry_owner', table_name='jewelry')
    op.create_index(op.f('ix_jewelry_owner_id'), 'jewelry', ['owner_id'], unique=False)
    op.drop_column('jewelry', 'owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jewelry', sa.Column('owner', sa.VARCHAR(length=64), nullable=False))
    op.drop_index(op.f('ix_jewelry_owner_id'), table_name='jewelry')
    op.create_index('ix_jewelry_owner', 'jewelry', ['owner'], unique=False)
    op.drop_column('jewelry', 'owner_id')
    op.drop_index(op.f('ix_sale_jewelery_id'), table_name='sale')
    op.drop_index(op.f('ix_sale_date'), table_name='sale')
    op.drop_table('sale')
    op.drop_index(op.f('ix_owner_name'), table_name='owner')
    op.drop_table('owner')
    # ### end Alembic commands ###
