"""entries table

Revision ID: 4c6d7e143099
Revises: 46dcd6a2f6b5
Create Date: 2024-04-12 22:59:17.590186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c6d7e143099'
down_revision = '46dcd6a2f6b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jewelry', 'is_bought')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jewelry', sa.Column('is_bought', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
