"""entries table

Revision ID: 70d88dee5373
Revises: 4c6d7e143099
Create Date: 2024-04-12 23:30:23.287180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d88dee5373'
down_revision = '4c6d7e143099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('price', sa.Float(), nullable=False))
    op.create_index(op.f('ix_purchase_price'), 'purchase', ['price'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_price'), table_name='purchase')
    op.drop_column('purchase', 'price')
    # ### end Alembic commands ###
