"""entries table

Revision ID: bb29dde66e38
Revises: 4b237dc20234
Create Date: 2024-04-22 21:56:13.811025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb29dde66e38'
down_revision = '4b237dc20234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('owner', sa.Column('surname', sa.String(length=64), nullable=False))
    op.create_index(op.f('ix_owner_surname'), 'owner', ['surname'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_owner_surname'), table_name='owner')
    op.drop_column('owner', 'surname')
    # ### end Alembic commands ###
