"""entries table

Revision ID: e958a66d3531
Revises: 8a48cd99eb4c
Create Date: 2024-05-18 17:22:41.055437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e958a66d3531'
down_revision = '8a48cd99eb4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('comm_id', sa.Integer(), nullable=False))
    op.drop_index('ix_purchase_owner_id', table_name='purchase')
    op.create_index(op.f('ix_purchase_comm_id'), 'purchase', ['comm_id'], unique=False)
    op.drop_column('purchase', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('owner_id', sa.INTEGER(), nullable=False))
    op.drop_index(op.f('ix_purchase_comm_id'), table_name='purchase')
    op.create_index('ix_purchase_owner_id', 'purchase', ['owner_id'], unique=False)
    op.drop_column('purchase', 'comm_id')
    # ### end Alembic commands ###
