"""entries table

Revision ID: fa9919816299
Revises: ec7c93a56c94
Create Date: 2024-04-12 22:17:54.754334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa9919816299'
down_revision = 'ec7c93a56c94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jewelry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jewelry_owner'), 'jewelry', ['owner'], unique=False)
    op.create_index(op.f('ix_jewelry_title'), 'jewelry', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jewelry_title'), table_name='jewelry')
    op.drop_index(op.f('ix_jewelry_owner'), table_name='jewelry')
    op.drop_table('jewelry')
    # ### end Alembic commands ###
